### PR TITLE
Escape " in paths on non-Win platforms

### PR DESCRIPTION
**Pull request by mickeypearce**
@rafael-trevisan , I cannot push to your fork so this is a continutation of #9 .

I did a replace of " with escaped " as you suggested for non-Win platform. I will be delighted if you could test. :)

### CODE REVIEW

**Comment by mickeypearce** [comment]
If it works you can update your original PR with this change, because I am not sure if It will count you as a contributor If I merge this PR. 😨

**Comment by rafael-trevisan** [comment]
I am still figuring it out how to get this change as a "local extension" so
I can actually test it.

It's okay if you change the code directly if you prefer to. I'll read how
to install the extension locally here anyway ;)

**Comment by mickeypearce** [comment]
Usually you run `npm install` from your local repo directory and then launch (press F5) extension in debug mode.

**Comment by mickeypearce** [comment]
Solved in #11.

**Pull request closed without merging**
