### PR TITLE
Fix issue with quotes

### PR DESCRIPTION
**Pull request by rafael-trevisan**
Closes https://github.com/mickeypearce/vscode-oracle-format/issues/5
Tested on MacOS with standard rules and custom style.xml rule file

### CODE REVIEW

**Comment by rafael-trevisan** [comment]
Hey @mickeypearce, I got the .vsix here and the proposed change works very well on MacOS. I've tested with the standard rules and a custom style.xml as well.

In the end, wasn't necessary to normalize any path. By debugging the code I could see where was missing the quotes 😉

**Comment by mickeypearce** [comment]
Sorry I am a bit confused. For working on Mac we must include changes from #10  and #11, is that correct? I can upload a vsix if you can test.

**Comment by rafael-trevisan** [comment]
Nope, only the last change. Sorry if it got confused. The only change needed is this:

const cmd = `"${sqlPath}" /nolog @"${formatScript}"`;

**Comment by mickeypearce** [comment]
No problem and thanks! I will test on Win and If it works I will merge and release in a few days.

**Comment by rafael-trevisan** [comment]
👍🏻

**Comment by rafael-trevisan** [comment]
Hi @mickeypearce, just wondering if you could test on Windows :)

**Comment by mickeypearce** [comment]
@rafael-trevisan , it works. thanks!

**Comment by rafael-trevisan** [comment]
Great! It works beautifully :)

**Pull request merged**
